<?php

$custom_alerts = [
    __( 'bbPress Forums', 'wsal-bbpress' ) => [
        __( 'Forums', 'wsal-bbpress' )                => [
            [
                8000,
                WSAL_INFORMATIONAL,
                __( 'User created new forum', 'wsal-bbpress' ),
                __( 'New forum called %1$ForumName%', 'wsal-bbpress' ),
                [],
                [ '%2$EditorLinkForum%' ],
                'bbpress-forum',
                'created',
            ],
            [
                8001,
                WSAL_MEDIUM,
                __( 'User changed status of a forum', 'wsal-bbpress' ),
                __( 'Changed the status of the forum %1$ForumName%', 'wsal-bbpress' ),
                [
                    __( 'Previous status: %OldStatus%', 'wsal-bbpress' ),
                    __( 'New status: %NewStatus%', 'wsal-bbpress' ),
                ],
                [
                    '%2$EditorLinkForum%',
                ],
                'bbpress-forum',
                'modified',
            ],
            [
                8002,
                WSAL_MEDIUM,
                __( 'User changed visibility of a forum', 'wsal-bbpress' ),
                __( 'Changed the visibility of the forum %1$ForumName%', 'wsal-bbpress' ),
                [
                    __( 'Previous visibility: %OldVisibility%', 'wsal-bbpress' ),
                    __( 'New visibility: %NewVisibility%', 'wsal-bbpress' ),
                ],
                [
                    '%2$EditorLinkForum%',
                ],
                'bbpress-forum',
                'modified',
            ],
            [
                8003,
                WSAL_LOW,
                __( 'User changed the URL of a forum', 'wsal-bbpress' ),
                __( 'Changed the URL of the forum %1$ForumName%', 'wsal-bbpress' ),
                [
                    __( 'Previous URL: %OldUrl%', 'wsal-bbpress' ),
                    __( 'New URL: %NewUrl%', 'wsal-bbpress' ),
                ],
                [
                    '%2$EditorLinkForum%',
                ],
                'bbpress-forum',
                'modified',
            ],
            [
                8004,
                WSAL_INFORMATIONAL,
                __( 'User changed order of a forum', 'wsal-bbpress' ),
                __( 'Changed the sorting order of the forum %1$ForumName%', 'wsal-bbpress' ),
                [
                    __( 'Previous sorting order: %OldOrder%', 'wsal-bbpress' ),
                    __( 'New sorting order: %NewOrder%', 'wsal-bbpress' ),
                ],
                [
                    '%2$EditorLinkForum%',
                ],
                'bbpress-forum',
                'modified',
            ],
            [
                8005,
                WSAL_HIGH,
                __( 'User moved forum to trash', 'wsal-bbpress' ),
                __( 'Moved the forum %ForumName% to trash', 'wsal-bbpress' ),
                [],
                [],
                'bbpress-forum',
                'deleted',
            ],
            [
                8006,
                WSAL_HIGH,
                __( 'User permanently deleted forum', 'wsal-bbpress' ),
                __( 'Permanently deleted the forum %ForumName%', 'wsal-bbpress' ),
                [],
                [],
                'bbpress-forum',
                'deleted',
            ],
            [
                8007,
                WSAL_HIGH,
                __( 'User restored forum from trash', 'wsal-bbpress' ),
                __( 'Restored the forum %ForumName% from trash', 'wsal-bbpress' ),
                [],
                [],
                'bbpress-forum',
                'restored',
            ],
            [
                8008,
                WSAL_LOW,
                __( 'User changed the parent of a forum', 'wsal-bbpress' ),
                __( 'Changed the parent of the forum %1$ForumName%', 'wsal-bbpress' ),
                [
                    __( 'Previous parent: %OldParent%', 'wsal-bbpress' ),
                    __( 'New parent: %NewParent%', 'wsal-bbpress' ),
                ],
                [
                    '%2$EditorLinkForum%',
                ],
                'bbpress-forum',
                'modified',
            ],
            [
                8011,
                WSAL_LOW,
                __( 'User changed type of a forum', 'wsal-bbpress' ),
                __( 'Changed the type of the forum %1$ForumName%', 'wsal-bbpress' ),
                [
                    __( 'Previous type: %OldType%', 'wsal-bbpress' ),
                    __( 'New type: %NewType%', 'wsal-bbpress' ),
                ],
                [
                    '%2$EditorLinkForum%',
                ],
                'bbpress-forum',
                'modified',
            ],
        ],

        __( 'bbPress Forum Topics', 'wsal-bbpress' )  => [
            [
                8014,
                WSAL_INFORMATIONAL,
                __( 'User created new topic', 'wsal-bbpress' ),
                __( 'New topic called %TopicName%', 'wsal-bbpress' ),
                [],
                [
                    '%EditorLinkTopic%',
                ],
                'bbpress-forum',
                'created',
            ],
            [
                8015,
                WSAL_INFORMATIONAL,
                __( 'User changed status of a topic', 'wsal-bbpress' ),
                __( 'Changed the status of the topic %TopicName%', 'wsal-bbpress' ),
                [
                    __( 'Previous status: %OldStatus%', 'wsal-bbpress' ),
                    __( 'New status: %NewStatus%', 'wsal-bbpress' ),
                ],
                [
                    '%EditorLinkTopic%',
                ],
                'bbpress-forum',
                'modified',
            ],
            [
                8016,
                WSAL_INFORMATIONAL,
                __( 'User changed type of a topic', 'wsal-bbpress' ),
                __( 'Changed the type of the topic %TopicName%', 'wsal-bbpress' ),
                [
                    __( 'Previous type: %OldType%', 'wsal-bbpress' ),
                    __( 'New type: %NewType%', 'wsal-bbpress' ),
                ],
                [
                    '%EditorLinkTopic%',
                ],
                'bbpress-forum',
                'modified',
            ],
            [
                8017,
                WSAL_INFORMATIONAL,
                __( 'User changed URL of a topic', 'wsal-bbpress' ),
                __( 'Changed the URL of the topic %TopicName%', 'wsal-bbpress' ),
                [
                    __( 'Previous URL: %OldUrl%', 'wsal-bbpress' ),
                    __( 'New URL: %NewUrl%', 'wsal-bbpress' ),
                ],
                [
                    '%EditorLinkTopic%',
                ],
                'bbpress-forum',
                'modified',
            ],
            [
                8018,
                WSAL_INFORMATIONAL,
                __( 'User changed the forum of a topic', 'wsal-bbpress' ),
                __( 'Changed the forum of the topic %TopicName%', 'wsal-bbpress' ),
                [
                    __( 'Previous forum: %OldForum%', 'wsal-bbpress' ),
                    __( 'New forum: %NewForum%', 'wsal-bbpress' ),
                ],
                [
                    '%EditorLinkTopic%',
                ],
                'bbpress-forum',
                'modified',
            ],
            [
                8019,
                WSAL_MEDIUM,
                __( 'User moved topic to trash', 'wsal-bbpress' ),
                __( 'Moved the %TopicName% to trash', 'wsal-bbpress' ),
                [],
                [],
                'bbpress-forum',
                'deleted',
            ],
            [
                8020,
                WSAL_MEDIUM,
                __( 'User permanently deleted topic', 'wsal-bbpress' ),
                __( 'Permanently deleted the topic %TopicName%', 'wsal-bbpress' ),
                [],
                [],
                'bbpress-forum',
                'deleted',
            ],
            [
                8021,
                WSAL_INFORMATIONAL,
                __( 'User restored topic from trash', 'wsal-bbpress' ),
                __( 'Restored the topic %TopicName% from trash', 'wsal-bbpress' ),
                [],
                [],
                'bbpress-forum',
                'restored',
            ],
            [
                8022,
                WSAL_LOW,
                __( 'User changed visibility of a topic', 'wsal-bbpress' ),
                __( 'Changed the visibility of the topic %TopicName%', 'wsal-bbpress' ),
                [
                    __( 'Previous visibility: %OldVisibility%', 'wsal-bbpress' ),
                    __( 'New visibility: %NewVisibility%', 'wsal-bbpress' ),
                ],
                [
                    '%EditorLinkTopic%',
                ],
                'bbpress-forum',
                'modified',
            ],
        ],

        __( 'bbPress Settings', 'wsal-bbpress' )      => [
            [
                8009,
                WSAL_HIGH,
                __( 'User changed forum\'s role', 'wsal-bbpress' ),
                __( 'Changed the bbPress setting <strong>Automatically give registered users a forum role</strong>', 'wsal-bbpress' ),
                [
                    __( 'Previous role: %OldRole%', 'wsal-bbpress' ),
                    __( 'New role: %NewRole%', 'wsal-bbpress' ),
                ],
                [],
                'bbpress',
                'modified',
            ],
            [
                8010,
                WSAL_CRITICAL,
                __( 'User changed option of a forum', 'wsal-bbpress' ),
                __( 'The bbPress setting <strong>Anonymous</strong> (allow guest users to post on the forums)', 'wsal-bbpress' ),
                [],
                [],
                'bbpress',
                'enabled',
            ],
            [
                8012,
                WSAL_MEDIUM,
                __( 'User changed time to disallow post editing', 'wsal-bbpress' ),
                __( 'Changed the time of the bbPress setting <strong>Editing</strong>E (to allow users to edit their content after posting)', 'wsal-bbpress' ),
                [
                    __( 'Previous time: %OldTime%', 'wsal-bbpress' ),
                    __( 'New time: %NewTime%', 'wsal-bbpress' ),
                ],
                [],
                'bbpress',
                'modified',
            ],
            [
                8013,
                WSAL_HIGH,
                __( 'User changed the forum setting posting throttle time', 'wsal-bbpress' ),
                __( 'Changed the time of the bbPress setting <strong>Flooding</strong> (throttling users setting)', 'wsal-bbpress' ),
                [
                    __( 'Previous time: %OldTime%', 'wsal-bbpress' ),
                    __( 'New time: %NewTime%', 'wsal-bbpress' ),
                ],
                [],
                'bbpress',
                'modified',
            ],
        ],

        __( 'bbPress User Profiles', 'wsal-bbpress' ) => [
            [
                8023,
                WSAL_LOW,
                __( 'The forum role of a user was changed by another WordPress user', 'wsal-bbpress' ),
                __( 'Change the role of user %TargetUsername%', 'wsal-bbpress' ),
                [
                    __( 'Previous role: %OldRole%', 'wsal-bbpress' ),
                    __( 'New role: %NewRole%', 'wsal-bbpress' ),
                    __( 'First name: %1$FirstName%', 'wsal-bbpress' ),
                ],
                [
                    '%2$EditUserLink%',
                ],
                'user',
                'modified',
            ],
        ],
    ],
];
