name: "WordPress Coding Standards review"

on: workflow_dispatch
    inputs:
      access_token:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Personal access token'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true

jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run PHPCS inspection
        uses: rtCamp/action-phpcs-code-review@v2
        env:
          GH_BOT_TOKEN: ${{ github.event.inputs.access_token }}
          SKIP_FOLDERS: ".github,tests,vendor"
